# fly.toml app configuration file generated for apte-dictionary on 2025-04-25T20:46:52+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#
# cd to the directory containing this file and run `fly deploy`

app = 'apte-dictionary'
primary_region = 'ams'

[build]

[env]
  DATA_DIR = '/app/data'
  NODE_ENV = 'production'
  PORT = '8080'

[[mounts]]
  source = 'apte_data'
  destination = '/app/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  size = 'shared-cpu-1x'
