module UtilsTemp where

import qualified Data.Map as M
import System.FilePath ((</>))
import qualified Data.ByteString.Lazy as BL
import qualified Data.Aeson as A
import qualified Data.Aeson.Encode.Pretty as E
import qualified Data.List as L
import qualified Data.Set as S
import System.IO.Unsafe (unsafePerformIO)
import Data.Maybe (fromMaybe)
import System.IO (stdout, stderr, Handle, hPutStrLn)
import Data.Function
import Data.Bifunctor

getXmlTagOccs :: String -> String -> [String]
getXmlTagOccs tag = reverse . flip go [] where
    go "" acc = acc
    go xs acc = if ("<"++tag++">") `L.isPrefixOf` xs then go2 (drop 4 xs) acc "" else go (tail xs) acc
    go2 "" acc tmp = acc
    go2 xs acc tmp = if ("</"++tag++">") `L.isPrefixOf` xs then go (drop 5 xs) (reverse tmp: acc) else go2 (tail xs) acc (head xs: tmp) 

-- Frequency (cumulative) distribution of references in Apte
getRefFreqCumulativePercent linesHavingLs = let
    refs = L.sort $ concat $ getXmlTagOccs "ls" <$> linesHavingLs
    refmap = M.fromListWith (++) $ second (:[]) . (span (/= '.')) <$> refs
    freqRef = reverse $ L.sortOn snd $ M.toList $ M.map length refmap
    total = fromIntegral $ sum $ fmap snd freqRef
    freqRefAggr = scanl (\(bs,bi) (as,ai) -> (as,bi+ai)) ("",0) freqRef
    freqRefAggrPercent = fmap (\(s,i)->(s, round (fromIntegral i * 100.0 / total))) freqRefAggr
    output = unlines $ fmap (\(s,i) -> s ++ "\t" ++ show i) freqRefAggrPercent
    in output

{-
[
    " 0",
    "R 13",
    "Ms 20",
    "Ś 26",
    "Ku 32",
    "Śi 38",
    "U 42",
    "K 46",
    "Pt 50",
    "Māl 53",
    "Ki 56",
    "Bk 60",
    "Me 62",
    "Bg 65",
    "Bh 67",
    "Y 69",
    "V 71",
    "Mu 73",
    "H 75",
    "M 77",
    "Dk 78",
    "Mk 79",
    "Bv 81",
    "Mv 82",
    "Sk 83",
    "P 85",
    "Mb 86",
    "Gīt 87",
    "Rām 88",
    "Ve 89",
    "S 90",
    "N 91",
    "Rv 91",
    "Amaru 92",
    "Subhāṣ 92",
    "Rs 93",
    "Ratn 93",
    "Malli 94",
    "Ak 94",
    "G 94",
    "Suśr 94",
    "Ch 95",
    "Vikr 95",
    "Śānti 95",
    "Mbh 95",
    "Śat 95",
    "Udb 95",
    "Nir 96",
    "Kāv 96",
    "Kull 96",
    "Ks 96",
    "Bhāg 96",
    "Chāṇ 96",
    "Ait 96",
    "T 97",
    "Sāy 97",
    "Bṛ 97",
    "Vb 97",
    "Tv 97",
    "Kāty 97",
    "Bhāṣā P 97",
    "Tarka K 97",
    "Mit 97",
    "Chandr 97",
    "Kām 97",
    "Hariv 97",
    "Āśval 97",
    "Śik 98",
    "Uṇ 98",
    "Prab 98",
    "Nala 98",
    "Śabdak 98",
    "Nāg 98",
    "Ghaṭ 98",
    "Br 98",
    "B 98",
    "Vop 98",
    "Sarva 98",
    "Vās 98",
    "Sāṅ 98",
    "Nalod 98",
    "Rāj 98",
    "Moha M 98",
    "Aśvad 98",
    "Śrut 98",
    "Śaṅkara 98",
    "Nārada 98",
    "Jag 98",
    "A 98",
    "Trik 98",
    "Mārk 98",
    "Bharata 98",
    "Kīr 98",
    "Kaṭh 98",
    "Vaiś 99",
    "Ud 99",
    "Ratimañjarī 99",
    "Kāśi 99",
    "J 99",
    "Halāy 99",
    "Dāy 99",
    "Bop 99",
    "Bhāva P 99",
    "Vet 99",
    "Vedānta 99",
    "Up 99",
    "Mīm 99",
    "Med 99",
    "Kātyāyana 99",
    "Kuval 99",
    "Ken 99",
    "Gaut 99",
    "Ā 99",
    "Vaijayantī 99",
    "Pratāparudra 99",
    "Nyāya S 99",
    "Mugdha 99",
    "Līlā 99",
    "Kāśikā 99",
    "Jagannātha 99",
    "Hārīta 99",
    "Chāt 99",
    "Chand 99",
    "Av 99",
    "Amara 99",
    "Śvet 99",
    "Śrāvaṇī Mantra 99",
    "Yv 99",
    "Yoga S 99",
    "Vāj 99",
    "Viṣṇu Smṛti 99",
    "Viṣṇu 99",
    "Vedānta S 99",
    "Udbhaṭa 99",
    "Sūrya S 99",
    "Sāv 99",
    "Subhāṣita 99",
    "Smṛti 99",
    "Pat 99",
    "Nīti 99",
    "Nyāya Sūtra 99",
    "Naiṣadha 99",
    "Muṇḍ 99",
    "Muktā 99",
    "Medhātithi 99",
    "Līlāvatī 99",
    "Kālikā P 99",
    "Kavirahasya 99",
    "Karpūr 99",
    "Jagaddhara 99",
    "Hārāvalī 99",
    "Hem 99",
    "Dhūrtas 99",
    "D 99",
    "Bṛhat Saṃhitā 99",
    "Śāṅkaradigvijaya 99",
    "Śāntilakṣaṇa 99",
    "Śukra 99",
    "Śrīdhara 99",
    "Śikṣā 99",
    "Śaṅkara Bhāṣya 99",
    "Śabarasvāmin 99",
    "Āryā S 99",
    "Ādipurāṇa 99",
    "Yādava 99",
    "Vāyu 99",
    "Vāk 99",
    "Vāgb 99",
    "Vopadeva 99",
    "Viśva 99",
    "Vedāntasāra 99",
    "Vedānta P 99",
    "Vasiṣṭha 99",
    "Uṇādisūtras 99",
    "Uśanas 99",
    "Ujjvalamaṇi 99",
    "Ujjval 99",
    "Tāṇḍya Br 99",
    "Tantra 99",
    "Sāṅkhyapravacanabhāṣya 99",
    "Sāṅkhya 99",
    "Sāyaṇa 99",
    "Saṃdhyā Mantra 99",
    "Sar 99",
    "Rāyamukuṭa 99",
    "Rāghavānanda 99",
    "Ratimañjarī 37 99",
    "Ratimañjarī 35 99",
    "Rasamañjarī 3-94 99",
    "Rasamañjarī 99",
    "Pūjāmantra 99",
    "Pūjā Mantra 99",
    "Puṣpadanta 99",
    "Praśna Up 99",
    "Praśn 99",
    "Pañcadaśī 99",
    "Paribhāṣenduśekhara 99",
    "Padma Purāṇa 99",
    "Pad 99",
    "Nītipr 99",
    "Mīmāmsā 99",
    "Māṇḍ 99",
    "Mādh 99",
    "Muhūrta 99",
    "Madhusūdana 99",
    "Kāmandaka 99",
    "Kālikā Purāṇa 99",
    "Kusum 99",
    "Kumārila 99",
    "Kauṣ 99",
    "Kauś 99",
    "Karka 99",
    "Kalhaṇa 99",
    "Kaiyaṭa 99",
    "Jābāli 99",
    "Jaimini S 99",
    "Hist 99",
    "Hemādri 99",
    "Hemacandra 99",
    "Hch 99",
    "Haima 99",
    "Golādh 99",
    "Gobhila 99",
    "Gaṅgāṣṭaka 99",
    "Gauḍapāda 99",
    "Gautama 99",
    "Gadādhara 99",
    "Dṛ 99",
    "Dīpikā 99",
    "Dhūrt 99",
    "Dharm 99",
    "Dhan 99",
    "Dakṣa 99",
    "Colebr 99",
    "Chān 99",
    "Caraka 99",
    "Candrāloka 99",
    "Bopadeva 99",
    "Bhāminīvilāsa 99",
    "Bhartṛhari 99",
    "Bhartṛ 99",
    "Atri 99",
    "Adhikaraṇamālā 100"
]

-}